# Generated by Django 4.1 on 2022-08-10 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subcode', models.CharField(max_length=100)),
                ('subname', models.CharField(max_length=100)),
                ('cno1', models.CharField(max_length=100)),
                ('cno2', models.CharField(max_length=100)),
                ('cno3', models.CharField(max_length=100)),
                ('cno4', models.CharField(max_length=100)),
                ('cno5', models.CharField(max_length=100)),
                ('co1', models.CharField(max_length=100)),
                ('co2', models.CharField(max_length=100)),
                ('co3', models.CharField(max_length=100)),
                ('co4', models.CharField(max_length=100)),
                ('co5', models.CharField(max_length=100)),
                ('cobj1', models.CharField(default='NA', max_length=100)),
                ('cobj2', models.CharField(default='NA', max_length=100)),
                ('cobj3', models.CharField(default='NA', max_length=100)),
                ('cobj4', models.CharField(default='NA', max_length=100)),
                ('cobj5', models.CharField(default='NA', max_length=100)),
                ('cobj6', models.CharField(default='NA', max_length=100)),
                ('cobj7', models.CharField(default='NA', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subjCode', models.CharField(max_length=10)),
                ('unit', models.CharField(max_length=10)),
                ('Qn', models.CharField(max_length=500)),
                ('Qnimg1', models.ImageField(max_length=10, upload_to='')),
                ('Qnimg2', models.ImageField(max_length=10, upload_to='')),
                ('Qnimg3', models.ImageField(max_length=10, upload_to='')),
                ('Ans', models.CharField(max_length=500)),
                ('ansimg1', models.ImageField(max_length=10, upload_to='')),
                ('ansimg2', models.ImageField(max_length=10, upload_to='')),
                ('ansimg3', models.ImageField(max_length=10, upload_to='')),
                ('mark_alloted', models.CharField(max_length=10)),
            ],
        ),
    ]
