# Generated by Django 4.1 on 2022-08-13 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='Qnimg1',
            field=models.ImageField(default='NA', max_length=10, upload_to=''),
        ),
        migrations.AlterField(
            model_name='questions',
            name='Qnimg2',
            field=models.ImageField(default='NA', max_length=10, upload_to=''),
        ),
        migrations.AlterField(
            model_name='questions',
            name='Qnimg3',
            field=models.ImageField(default='NA', max_length=10, upload_to=''),
        ),
        migrations.AlterField(
            model_name='questions',
            name='ansimg1',
            field=models.ImageField(default='NA', max_length=10, upload_to=''),
        ),
        migrations.AlterField(
            model_name='questions',
            name='ansimg2',
            field=models.ImageField(default='NA', max_length=10, upload_to=''),
        ),
        migrations.AlterField(
            model_name='questions',
            name='ansimg3',
            field=models.ImageField(default='NA', max_length=10, upload_to=''),
        ),
    ]
