# Generated by Django 4.1 on 2022-08-13 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_questions_qnimg1_alter_questions_qnimg2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='BT_Level',
            field=models.CharField(default='NA', max_length=20),
        ),
        migrations.AddField(
            model_name='questions',
            name='CO',
            field=models.CharField(default='NA', max_length=10),
        ),
        migrations.AddField(
            model_name='questions',
            name='Univ_QP_Reference',
            field=models.CharField(default='NA', max_length=100),
        ),
    ]
